# Generated by Django 4.2.7 on 2025-07-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_alter_attendance_options_and_more'),
        ('excuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcuseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo adjunto', upload_to='excuse_attachments/%Y/%m/')),
                ('file_name', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('file_type', models.CharField(help_text='Tipo MIME del archivo', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto de Excusa',
                'verbose_name_plural': 'Adjuntos de Excusa',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcuseReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Comentario sobre el cambio de estado', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Revisión de Excusa',
                'verbose_name_plural': 'Logs de Revisión de Excusa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcuseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la plantilla', max_length=100)),
                ('excuse_type', models.CharField(choices=[('medical', 'Médica'), ('family', 'Familiar'), ('work', 'Laboral'), ('academic', 'Académica'), ('transport', 'Transporte'), ('other', 'Otra')], help_text='Tipo de excusa', max_length=20)),
                ('template_text', models.TextField(help_text='Texto base de la plantilla')),
                ('is_active', models.BooleanField(default=True, help_text='Plantilla activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Excusa',
                'verbose_name_plural': 'Plantillas de Excusa',
                'ordering': ['excuse_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='excuse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Excusa', 'verbose_name_plural': 'Excusas'},
        ),
        migrations.AddField(
            model_name='excuse',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Información de contacto adicional si es necesaria', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='excuse',
            name='excuse_type',
            field=models.CharField(choices=[('medical', 'Médica'), ('family', 'Familiar'), ('work', 'Laboral'), ('academic', 'Académica'), ('transport', 'Transporte'), ('other', 'Otra')], default='other', help_text='Tipo de excusa', max_length=20),
        ),
        migrations.AddField(
            model_name='excuse',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Marca si la excusa requiere revisión urgente'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la excusa'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='document',
            field=models.FileField(blank=True, help_text='Documento de soporte (opcional)', null=True, upload_to='excuses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='reason',
            field=models.TextField(help_text='Descripción detallada de la excusa'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='review_comment',
            field=models.TextField(blank=True, help_text='Comentarios del instructor sobre la revisión', null=True),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de revisión de la excusa', null=True),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Instructor que revisó la excusa', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='session',
            field=models.ForeignKey(help_text='Sesión para la cual se presenta la excusa', on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de la excusa', max_length=20),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='student',
            field=models.ForeignKey(help_text='Estudiante que presenta la excusa', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_excuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='excuse',
            index=models.Index(fields=['status', 'created_at'], name='excuses_exc_status_1e86cd_idx'),
        ),
        migrations.AddIndex(
            model_name='excuse',
            index=models.Index(fields=['student', 'status'], name='excuses_exc_student_db52d2_idx'),
        ),
        migrations.AddIndex(
            model_name='excuse',
            index=models.Index(fields=['session', 'status'], name='excuses_exc_session_b909b0_idx'),
        ),
        migrations.AddField(
            model_name='excusetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_excuse_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excusereviewlog',
            name='excuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='excuses.excuse'),
        ),
        migrations.AddField(
            model_name='excusereviewlog',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuse_reviews_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excuseattachment',
            name='excuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='excuses.excuse'),
        ),
    ]
