# Generated by Django 4.2.7 on 2025-09-02 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_attendance_options_and_more'),
        ('excuses', '0002_excuseattachment_excusereviewlog_excusetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excuseattachment',
            name='excuse',
        ),
        migrations.RemoveField(
            model_name='excusereviewlog',
            name='excuse',
        ),
        migrations.RemoveField(
            model_name='excusereviewlog',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='excusetemplate',
            name='created_by',
        ),
        migrations.RemoveIndex(
            model_name='excuse',
            name='excuses_exc_status_1e86cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='excuse',
            name='excuses_exc_student_db52d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='excuse',
            name='excuses_exc_session_b909b0_idx',
        ),
        migrations.RemoveField(
            model_name='excuse',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='excuse',
            name='excuse_type',
        ),
        migrations.RemoveField(
            model_name='excuse',
            name='is_urgent',
        ),
        migrations.AlterField(
            model_name='excuse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='excuses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='excuse',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_excuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExcuseAttachment',
        ),
        migrations.DeleteModel(
            name='ExcuseReviewLog',
        ),
        migrations.DeleteModel(
            name='ExcuseTemplate',
        ),
    ]
