# Generated by Django 4.2.7 on 2025-07-29 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_ficha_options_alter_student_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-session__date', 'student__last_name', 'student__first_name'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Sesión de Asistencia', 'verbose_name_plural': 'Sesiones de Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_confidence_score',
            field=models.FloatField(blank=True, help_text='Puntuación de confianza del reconocimiento facial (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Indica si la asistencia fue modificada manualmente por el instructor'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la modificación manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Razón de la modificación manual', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_closed',
            field=models.BooleanField(default=False, help_text='Indica si se cerró la toma de asistencia'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_closed_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se cerró la toma de asistencia', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_started',
            field=models.BooleanField(default=False, help_text='Indica si ya se inició la toma de asistencia'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_started_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se inició la toma de asistencia', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='late_tolerance_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutos de tolerancia para considerar tardanza'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del curso', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='fichas',
            field=models.ManyToManyField(blank=True, help_text='Fichas que participan en este curso', related_name='courses', to='authentication.ficha'),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_per_session',
            field=models.PositiveIntegerField(default=2, help_text='Horas por sesión de clase'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Curso activo'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Momento exacto en que se registró la asistencia', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_by_face',
            field=models.BooleanField(default=False, help_text='Indica si la asistencia fue verificada por reconocimiento facial'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.course'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de la sesión'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(help_text='Hora de finalización de la sesión'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Sesión activa para toma de asistencia'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(help_text='Hora de inicio de la sesión'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Código único del curso', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Nombre del curso o materia', max_length=100),
        ),
    ]
