# Generated by Django 4.2.7 on 2025-09-02 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='face_confidence_score',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='manual_override',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='override_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_by_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_formacion', models.CharField(max_length=100)),
                ('numero_ficha', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='fichas_enrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.ficha'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('ficha', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance_closed',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance_closed_at',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance_started',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='attendance_started_at',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='late_tolerance_minutes',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
