# Generated by Django 4.2.7 on 2025-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='permisividad',
            field=models.IntegerField(default=0, help_text='Minutos de permisividad para llegar tarde'),
        ),
    ]
