# Generated by Django 4.2.7 on 2025-07-28 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True)),
                ('numero_ficha', models.CharField(help_text='Número de ficha del curso al que pertenece', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del estudiante', max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del estudiante', null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único de la ficha', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la ficha/programa', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del programa de formación', null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del programa', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha estimada de finalización', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la ficha está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_coordinador', models.ForeignKey(blank=True, help_text='Instructor coordinador de la ficha', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_coordinadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['numero'],
            },
        ),
    ]
