# Generated by Django 4.2.7 on 2025-07-29 09:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_ficha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'ordering': ['-fecha_inicio', 'numero'], 'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='instructor_coordinador',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numero_ficha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='ficha',
            name='duracion_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Duración del programa en meses', null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='max_estudiantes',
            field=models.PositiveIntegerField(default=30, help_text='Número máximo de estudiantes permitidos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tipo_programa',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('especialista', 'Especialista'), ('curso_corto', 'Curso Corto')], default='tecnico', help_text='Tipo de programa de formación', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, help_text='Nombre del contacto de emergencia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contacto_emergencia_relacion',
            field=models.CharField(blank=True, help_text='Relación con el contacto de emergencia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del contacto de emergencia', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='estado_academico',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('retirado', 'Retirado'), ('graduado', 'Graduado'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado académico del aprendiz', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso al programa'),
        ),
        migrations.AddField(
            model_name='student',
            name='ficha',
            field=models.ForeignKey(default=1, help_text='Ficha a la que pertenece el aprendiz', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='authentication.ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='CC', help_text='Tipo de documento de identidad', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_sena',
            field=models.BooleanField(default=True, help_text='Usuario activo en el sistema SENA'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2099, 12, 31), help_text='Fecha estimada de finalización'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2025, 7, 29), help_text='Fecha de inicio del programa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nombre',
            field=models.CharField(help_text='Nombre del programa de formación', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(2025, 7, 29), help_text='Fecha de nacimiento del aprendiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del aprendiz', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='profiles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Aprendiz'), ('instructor', 'Instructor'), ('admin', 'Administrador')], default='student', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(help_text='Número de documento de identidad', max_length=20, unique=True)),
                ('telefono', models.CharField(help_text='Número de teléfono del instructor', max_length=15)),
                ('especialidades', models.TextField(help_text='Especialidades y áreas de conocimiento del instructor')),
                ('titulo_profesional', models.CharField(help_text='Título profesional del instructor', max_length=100)),
                ('experiencia_anos', models.PositiveIntegerField(default=0, help_text='Años de experiencia como instructor')),
                ('fecha_ingreso_sena', models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso al SENA')),
                ('is_active', models.BooleanField(default=True, help_text='Instructor activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
