# Generated by Django 4.2.7 on 2025-07-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_ficha_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha estimada de finalización'),
        ),
    ]
