# Generated by Django 4.2.7 on 2025-09-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
        ('authentication', '0004_alter_ficha_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_last_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='face_registered_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_sena',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('instructor', 'Instructor'), ('admin', 'Administrador')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ficha',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
